crowdfunder/config/routes.rb
Rails.application.routes.draw do

  get 'pledges/create'

  root :to => 'projects#index'

  resources :users, only: [:new, :create]
  resources :projects
  resources :user_sessions, only:[:new, :create, :destroy]
  resources :pledges, only:[:create]

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

crowdfunder/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

crowdfunder/app/models/pledge.rb
class Pledge < ActiveRecord::Base

  belongs_to :user
  belongs_to :reward
  has_one :project, through: :reward
end

crowdfunder/app/models/project.rb
class Project < ActiveRecord::Base
  has_many :rewards
  has_many :pledges, through: :rewards
  has_many :users, through: :pledges
  belongs_to :owner, class_name: "User"

  accepts_nested_attributes_for :rewards, reject_if: :all_blank, allow_destroy: true

  def remaining
    goal - pledges.sum(:amount)
  end

end

crowdfunder/app/models/reward.rb
class Reward < ActiveRecord::Base

  belongs_to :project
  has_many :users, through: :pledges
  has_many :pledges
end

crowdfunder/app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  has_many :pledges
  has_many :backed_projects, class_name: "Project", through: :pledges
  has_many :owned_projects, class_name: "Project", foreign_key: "owner_id"
  has_many :rewards, through: :pledges

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes["password"] }
  validates :password, confirmation: true, if: -> { new_record? || changes["password"] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"] }

  validates :email, uniqueness: true
end

crowdfunder/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



  private
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

crowdfunder/app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  def create
    @pledge = Pledge.new(pledge_params)
    @pledge.user_id = current_user.id
    @pledge.save
    @project = @pledge.project

    respond_to do |format|
      format.js
    end
  end

  private
  def pledge_params
    params.require(:pledge).permit(:amount, :reward_id)
  end
end

crowdfunder/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :require_login, only: [:new, :create]
  def new
    @project = Project.new
    @reward = @project.rewards.build
  end

  def create
    @project = Project.new(project_params)
    @project.owner_id = current_user.id
    if @project.save
      redirect_to projects_path
      else
        render :new
    end
  end

  def index
    @projects = Project.all
    #  authorize! :index, @project
  end

  def show
    @project = Project.find(params[:id])
    # authorize! :show, @project





  end

  def destroy
  end

  def edit
  end

  def update
  end

private

  def project_params
    params.require(:project).permit(:title, :description, :goal, :start_date, :end_date, rewards_attributes:[:name, :description, :amount_required])
  end
end

crowdfunder/app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(projects_url, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(login_url, notice: 'Logged out!')
  end
end

crowdfunder/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to projects_path
      else
        render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :avatar)
  end
end

crowdfunder/app/helpers/application_helper.rb
module ApplicationHelper
end

crowdfunder/app/helpers/pledges_helper.rb
module PledgesHelper
end

crowdfunder/app/helpers/projects_helper.rb
module ProjectsHelper
  def amountRemaining
    @project.goal - @project.pledges.sum(:amount)
  end

  def time_remaining
    if (@project.end_date.to_i < Time.now.to_i)
      '0'
    else
      ((@project.end_date.to_i - Time.now.to_i)/86400)
    end

  end


# Length of campaign: <%= ((@project.end_date.to_i - Time.now.to_i)/86400)  %> <br>
# Days remaining: <%= distance_of_time_in_words_to_now(@project.end_date) %>


  # if the current date is between the start and end date, then
  # days_remaining = end_date - current_date
  # else if the current date is before the start date, then replace "days remaining"
  # with " This project has yet to start"
  # else if the end date is before the current date, replace "days remaining"
  # with "This funding period is over".
end

crowdfunder/app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

crowdfunder/app/helpers/users_helper.rb
module UsersHelper
end

crowdfunder/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="nav">
    <% if current_user %>
      <% if current_user.avatar %>
        <%= image_tag image_path(current_user.avatar.url(:small_thumb)) %> 
      <% end %>
    <%= link_to "Logout", :logout, method: :post %>
    <% else %>
      <%= link_to "Register", new_user_path %> |
      <%= link_to "Login", :login %>
    <% end %>
  </div>
  <div>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>

<%= yield %>

</body>
</html>

crowdfunder/app/views/pledges/create.js.erb
//change the goal amount remaining
$('#amount-remaining').html(<%= @project.remaining %>);

//hide the pledge button

crowdfunder/app/views/projects/_reward_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :amount_required %>
    <%= f.number_field :amount_required, placeholder: 'Please enter a dollar amount' %>
  </div>

  <%= link_to_remove_association "remove reward", f %>
</div>

crowdfunder/app/views/projects/_rewards.html.erb
<% @project.rewards.each do |reward| %>
  <%= form_for Pledge.new do |f| %>
   <button class="reward">
    <span class="info">name: <%= reward.name %> <br>
    description: <%= reward.description %> <br>
    amount: <%= reward.amount_required %></span>
    <span class="pledge">
      Pledge now.
    </span>
  </button>
  <%= f.hidden_field :reward_id, value: reward.id %>
  <%= f.hidden_field :amount, value: reward.amount_required %>
  <% end %>
  <br> <br>
<% end %>

crowdfunder/app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

crowdfunder/app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

crowdfunder/app/views/projects/index.html.erb
<h1>Projects</h1>

<% @projects.each do |project| %>
  <%= link_to project.title, project_url(project.id) %> <br>
<% end %>

crowdfunder/app/views/projects/new.html.erb
<h1>Add Project</h1>

<%= form_for(@project) do |f| %>

    <div class="field">
      <%= f.label :title %> <br />
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :description %> <br />
      <%= f.text_area :description %>
    </div>

    <div class="field">
      <%= f.label :goal %> <br />
      <%= f.number_field :goal , placeholder: "Please enter a dollar amount" %>
    </div>

    <div class="field">
      <%= f.label :start_date %> <br />
      <%= f.date_field :start_date %>
    </div>

    <div class="field">
      <%= f.label :end_date %> <br />
      <%= f.date_field :end_date %>
    </div>

    <h1> Add Rewards </h1>

    <div id="rewards">
      <%= f.fields_for :rewards do |reward| %>
        <%= render 'reward_fields', f: reward %>
      <% end %>
    </div>

    <div class="links">
      <%= link_to_add_association 'add reward', f, :rewards %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>

<% end %>

crowdfunder/app/views/projects/show.html.erb
<h1><%= @project.title %> </h1>

Description: <%= @project.description %> <br>
Goal: $<%= @project.goal %> <br>
Remaining: $<span id="amount-remaining"><%= @project.remaining %></span>
Start_date: <%= @project.start_date.to_date %> <br>
End_date: <%= @project.end_date.to_date %> <br><br>

 Days remaining: <%= time_remaining %>

<h2>Reward(s)</h2>

<%= render "rewards" %>


<%= link_to "back to project", projects_path %>

crowdfunder/app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>

crowdfunder/app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

crowdfunder/app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

crowdfunder/app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

crowdfunder/app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

crowdfunder/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
   <%= f.label :email %><br />
   <%= f.email_field :email %>
</div>
<div class="field">
   <%= f.label :password %><br />
   <%= f.password_field :password %>
</div>

<div class="field">
   <%= f.label :password_confirmation %><br />
   <%= f.password_field :password_confirmation %>
</div>

<div class="field">
<%= f.label :avatar %>
<%= f.file_field :avatar %>
</div>

<div class="actions">
  <%= f.submit %>
</div>

<% end %>

crowdfunder/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

crowdfunder/app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class="signup_form">
  <%= render "form" %>
</div>